name: Lint Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile'
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - 'Dockerfile'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
