name: Lint Dockerfile

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/hadolint.yml
      - Dockerfile

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: hadolint/hadolint-action@master
        with:
          dockerfile: Dockerfile
