name: Test

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yml
      - action.yml
  pull_request:
    types: [ opened, synchronize, reopened ]  # Same as default
    paths:
      - .github/workflows/test.yml
      - action.yml
  workflow_run:
    workflows: [ Docker image ]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test expect to match
        uses: ./
        with:
          file1: test/expected.pdf
          file2: test/actual.pdf
          options: --verbose

      - name: Test view the difference
        uses: ./
        with:
          file1: test/a.pdf
          file2: test/b.pdf
          options: --skip-identical --output-diff=test/diff.pdf --dpi=100
          suppress-diff-error: true

      - uses: actions/upload-artifact@v3
        with:
          path: test/*.pdf
        if: always()

  test-review-rendered-with-japanese-font-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Output diff file
        uses: ./
        with:
          file1: test/review_japanese_1.pdf
          file2: test/review_japanese_2.pdf
          options: --output-diff=test/review_japanese_diff_actual.pdf
          suppress-diff-error: true

      - name: Verify diff file
        uses: ./
        with:
          file1: test/review_japanese_diff_expected.pdf
          file2: test/review_japanese_diff_actual.pdf
          options: --verbose
